---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "http://fambul.github.io/donboscofambul"
title: "Don Bosco Fambul"
canonifyurls: true
...

[params]
  description = ""
  mainIcon = "/img/donbosco.png"

[[params.social]]
    title = "Projekt 1"
    url = "https://twitter.com/SBootstrap"
[[params.social]]
    title = "Projekt 2"
    url = "https://github.com/IronSummitMedia/startbootstrap"
[[params.social]]
    title = "Projekt 3"
    url = ""
