---
baseurl: "http://fambul.github.io/donboscofambul"
languageCode: "en-us"
publishdir: "public"
contentdir: "content"
layoutdir: "layouts"
canonifyurls: true
title: "Don Bosco Fambul"
theme: "hugo-base-theme"
params: 
  mainIcon: "/img/donbosco.png"
  social: 
    title: "Projekt 1"
    url: "https://twitter.com/SBootstrap"
...
