---
baseurl: "http://fambul.github.io/donboscofambul"
languageCode: "en-us"
publishdir: "public"
contentdir: "content"
layoutdir: "layouts"
canonifyurls: true
title: "Don Bosco Fambul"
theme: "hugo_theme_beg"

Params:
  Author: "Don Bosco Fambul"
  DateForm: "Mon, Jan 2, 2006"
  GoogleAnalyticsUserID: "UA-55005303-5"
  Facebook: "donboscofambul"
  ShowRelatedPost: True
  Disqus: "unresolved"
  SyntaxHighlightTheme: "github.min.css"

Indexes:
  tag: "tags"

permalinks:
  post: /blog/:year/:month/:day/:slug/

MetadataFormat: "yaml"
