---
baseurl: "http://fambul.github.io/donboscofambul"
languageCode: "en-us"
publishdir: "public"
contentdir: "content"
layoutdir: "layouts"
canonifyurls: true
title: "Don Bosco Fambul"
theme: "twentyfourteen"
