#baseurl = "http://localhost/"
baseurl = "http://fambul.github.io/donboscofambul"
languageCode = "en-us"
title = "Don Bosco Fambul"
theme = "hugo-base-theme"

[params]
  description = ""
  mainIcon = "/img/donbosco.png"

[[params.social]]
    title = "Projekt 1"
    url = "https://twitter.com/SBootstrap"
[[params.social]]
    title = "Projekt 2"
    url = "https://github.com/IronSummitMedia/startbootstrap"
[[params.social]]
    title = "Projekt 3"
    url = ""

