---
contentdir: "content"
layoutdir:  "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "http://fambul.github.io/donboscofambul"
title: "Don Bosco Fambul"
canonifyurls: true
theme: "hugo-base-theme"
params:
  - description: "Don Bosco Fambul"
  - mainIcon: "/img/donbosco.png"
  - social:
    - titlei: "Projekt 1"
    - url: "https://twitter.com/SBootstrap"
  - social:
    - titlei: "Projekt 2"
    - url: "https://twitter.com/SBootstrap"
  - social:
    - titlei: "Projekt 3"
    - url: "https://twitter.com/SBootstrap"
    
...
