#baseurl = "http://www.donboscofambul.org/"
baseurl = "http://localhost/"
languageCode = "en-us"
title = "Don Bosco Fambul"

[params]
  description = ""
  mainIcon = "/img/donbosco.png"

[[params.social]]
    title = "Projekt 1"
    url = "https://twitter.com/SBootstrap"
[[params.social]]
    title = "Projekt 2"
    url = "https://github.com/IronSummitMedia/startbootstrap"
[[params.social]]
    title = "Projekt 3"
    url = ""

